### ISSUE TITLE
Object Reference Error When IsCellFlyoutEnabled is Set to True

### ISSUE THREAD

**Issue by jwadel** [telerik/UI-For-UWP#242] opened 2018-02-09 13:08 UTC
I used **RadDataGrid** with the **AutoGenerateColumns** property set to "**False**".  In order to show a tooltip for a particular **DataGridTextColumn** column, I set its **IsCellFlyoutEnabled** property to "**True**". This works well in **v1.0.0.7** but is broken in **v1.0.0.9**.

```
<telerikGrid:RadDataGrid x:Name="DataGrid" AutoGenerateColumns="False" >
  <telerikGrid:RadDataGrid.Columns>
    <telerikGrid:DataGridTextColumn x:Name="TitleColumn" PropertyName="Title" Header="Title" IsCellFlyoutEnabled="True"/>
  </telerikGrid:RadDataGrid.Columns>
</telerikGrid:RadDataGrid>
```

> Stack trace          

`System.NullReferenceException: Object reference not set to an instance of an object.   at Telerik.UI.Xaml.Controls.Grid.DataGridColumn.PrepareCell(GridCellModel cell)   at Telerik.UI.Xaml.Controls.Grid.Commands.CellFlyoutActionCommand.Execute(Object parameter)   at Telerik.UI.Xaml.Controls.Primitives.CommandServiceBase'1.ExecuteCommandCore(Int32 id, Object parameter, Boolean searchUser)   at Telerik.UI.Xaml.Controls.Grid.RadDataGrid.CellFlyoutTimerAnimationBoardCompleted(Object sender, Object e)
`

**Comment by APopatanasov** [comment] 2018-02-09 13:29
@jwadel  I was able to reproduce the observed exception. It is caused by a missed check for null value. With the latest release we made some changes with the columns structure and introduced some virtual methods that help building custom columns and the observed exception was caused by that changes and a missed scenario with the IsCellFlyoutEnabled.

In order to fix the issue the Prepare cell method should contain a check for null for the parent row and everything should be working as expected:
[https://github.com/telerik/UI-For-UWP/blob/7f10c53e5b7bbe21d599f27bd3a347e74c7ea0d5/Controls/Grid/Grid.UWP/View/Columns/DataGridColumn.Cells.cs#L160](https://github.com/telerik/UI-For-UWP/blob/7f10c53e5b7bbe21d599f27bd3a347e74c7ea0d5/Controls/Grid/Grid.UWP/View/Columns/DataGridColumn.Cells.cs#L160)

Something like:
`this.PrepareCell(cell.Container, cell.Value, cell.ParentRow?.ItemInfo.Item);`

If you are interested you could fix the issue by yourself and make a pull request. After that I will review it and if everything is fine the fix will be included in the next package.

I hope the provided information is helpful for you.

**Closed** 2018-05-23 06:07 UTC
Labels: area:grid, bug, effort: easy (hours), severity:high, status: Done
