### ISSUE TITLE
Designer view in VS2017 crashes when highlighing telerik xaml elements in xaml view

### ISSUE THREAD

**Issue by schnitty** [telerik/UI-For-UWP#97] opened 2017-05-24 02:25 UTC
Steps to reproduce:
New project
Add Telerik.Ui.for.UniversalWindowsPlatform nuget package
Add RadialGauge control
Set some properties.
Highlight some XAML code to copy and paste or whatever

An unhandled exception has occurred: (sorry for the image instead of text.  But VS2017 is locked up in this state so I can't select the text

![telerikissue](https://cloud.githubusercontent.com/assets/6099451/26384331/ae8d4cea-4077-11e7-8d19-4240786e0ba3.png)

At the moment these controls are unusable.  Have had a day worth of fiddling and crashes constantly.

**Comment by schnitty** [comment] 2017-05-24 05:13
It seems that v1.0.0.2 has introduced this.  Don't have the same issue with v1.0.0.1

**Comment by APopatanasov** [comment] 2017-05-25 06:43
Hi @schnitty,
We have tried to reproduce the described bu you crash using the provided steps, but without any success. Please, check the following video and let me know if something is missed that could help us reproduce the crash - for the test the 1.0.0.2 version is used and the latest official released version of Visual Studio 2017:
[https://www.screencast.com/t/BcxLRN9A6](https://www.screencast.com/t/BcxLRN9A6)

Looking forward to hearing from you.

**Comment by APopatanasov** [comment] 2017-05-25 07:31
We were able to reproduce it with #96 . No further information is needed. 😊

**Comment by schnitty** [comment] 2017-05-26 01:23
Even on v 1.0.0.1 I am getting a lot of visual studio crashes when I happen to select on a Telerik control in the xaml

**Comment by schnitty** [comment] 2017-05-26 01:52
So I have already had five crashes of Visual Studio 2017 in two hours this morning on v 1.0.0.1 related to the RadRadialGauge control.  After restarting Visual Studio then no designers will load for any pages even ones with out a telerik control on them.  I have to restart windows and open up app on a page without a telerik control and the designer view opens up ok.  I then have to walk around the page that does have the gauge very carefully to not upset it so that it breaks it and then I have to repeat.

**Comment by APopatanasov** [comment] 2017-05-26 07:01
Could you please provide us a stack traces of the observed by you crashes with the older version of the package? Using it we will be able to investigate them further and try to resolve them.

**Comment by schnitty** [comment] 2017-05-26 08:51
Will do next time it happens if I can.  When it happens it locks up Visual Studio and can only do anything by restarting so quite hard to get the stack trace as the UI freezes.  At the moment it seems to be working ok after updating Windows 10 to Creators update from anniversary update earlier today so I want to try and use this time to catch up on the time lost so far.  So don't want to go out of my way to break it at the moment, hope you understand.

**Comment by schnitty** [comment] 2017-05-26 13:21
Takes about 5 - 10 minutes before it eventually comes up with this exception.

System.NullReferenceException
Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.SDKThemeContentDocumentRootResolver.ProvideResolvedUriForSDKContent(Uri relativeUri, String sourcePath)
   at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.SDKThemeContentDocumentRootResolver.GetDocumentRoot(String path)
   at Microsoft.VisualStudio.DesignTools.Designer.Utility.ResourceSite.GetResolvedDocumentRootForSourceUri(IDocumentRootResolver documentRootResolver, DocumentCompositeNode resourceDictionaryNode, ICollection`1 warnings)
   at Microsoft.VisualStudio.DesignTools.Designer.Utility.ResourceSite.FindResourceInChildDictionary(IDocumentRootResolver documentRootResolver, XamlResourceKey key, ICollection`1 resourcesHostNodePath, ICollection`1 relatedRoots, ResourceDictionaryLink container, ICollection`1 warnings, DocumentCompositeNode resourceDictionaryReferenceNode)
   at Microsoft.VisualStudio.DesignTools.Designer.Utility.ResourceSite.FindResource(IDocumentRootResolver documentRootResolver, XamlResourceKey key, ICollection`1 resourcesHostNodePath, ICollection`1 relatedRoots, ResourceDictionaryLink container, Int32 numberOfChildrenToSearch, ICollection`1 warnings)
   at Microsoft.VisualStudio.DesignTools.Designer.Utility.ExpressionEvaluator.EvaluateResourceAtSpecificSite(ResourceSite resourceSite, XamlResourceKey key, ICollection`1 resourcesHostNodePath, ICollection`1 relatedRoots, Int32 lastResourceToSearch, ICollection`1 warnings, Boolean canReturnResourceTypeNode, Boolean evaluateRecursively, ICollection`1 seen)
   at Microsoft.VisualStudio.DesignTools.Designer.Utility.ExpressionEvaluator.EvaluateResourceAtSpecificNode(DocumentNode node, XamlResourceKey key, ICollection`1 resourcesHostNodePath, ICollection`1 relatedRoots, ICollection`1 warnings, Boolean canReturnResourceTypeNode, Boolean evaluateRecursively)
   at Microsoft.VisualStudio.DesignTools.Designer.Utility.ExpressionEvaluator.EvaluateResourceAndCollectionPath(DocumentNodePath nodePath, ResourceReferenceType referenceType, XamlResourceKey key, ICollection`1 resourcesHostNodePath, ICollection`1 relatedRoots, ICollection`1 warnings, Boolean& invalidForwardReference, Boolean canReturnResourceTypeNode, Boolean evaluateRecursively)
   at Microsoft.VisualStudio.DesignTools.Designer.Utility.ExpressionEvaluator.EvaluateExpression(DocumentNodePath context, DocumentNode expression)
   at Microsoft.VisualStudio.DesignTools.Designer.Utility.ResourceHelper.FindReferencedResourcesInternal(DocumentNode root, IDocumentRootResolver documentRootResolver, Dictionary`2 visited, IList`1 resources)
   at Microsoft.VisualStudio.DesignTools.Designer.Utility.ResourceHelper.FindReferencedResourcesInternal(DocumentNode root, IDocumentRootResolver documentRootResolver, Dictionary`2 visited, IList`1 resources)
   at Microsoft.VisualStudio.DesignTools.Designer.Utility.ResourceHelper.FindReferencedResources(DocumentNode root, IDocumentRootResolver documentRootResolver)
   at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.FindResource(ResourceDictionaryContentProvider themeContent, IDocumentRootResolver documentRootResolver, String originalThemePath, String applicationThemeKey, Func`2 provideInstanceForThemeContent, Func`3 provideResolvedUriForMergedDictionary, Func`2 provideContentForMergedDictionary, XamlResourceKey key, IList`1& auxiliaryResources)
   at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.FindResource(ResourceDictionaryContentProvider themeContent, IDocumentRootResolver documentRootResolver, String originalThemePath, String applicationThemeKey, Func`2 provideInstanceForThemeContent, Func`3 provideResolvedUriForMergedDictionary, Func`2 provideContentForMergedDictionary, XamlResourceKey key, IList`1& auxiliaryResources)
   at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.GetResourceInternal(Dictionary`2 themeCache, IPlatform platform, IDocumentRootResolver documentRootResolver, String path, IAssembly themeAssembly, String relativeThemePath, IProjectContext projectContext, Func`3 provideResolvedUriForMergedDictionary, Func`2 provideContentForMergedDictionary, XamlResourceKey key, IList`1& auxiliaryResources)
   at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.GetThemeResourceFromSdk(IProjectContext projectContext, IAssembly sdkAssembly, String sdkUniqueId, XamlResourceKey resourceKey, IList`1& auxiliaryResources)
   at Microsoft.VisualStudio.DesignTools.XamlDesigner.Commands.ReplaceStyleTemplateCommand.ResolveDefaultStyle(SceneNode targetElement, Object defaultStyleKey, Boolean allowDefaultStyle, DocumentNode& currentStyle, Boolean& isThemeStyle, IList`1& auxiliaryResources)
   at Microsoft.VisualStudio.DesignTools.XamlDesigner.Commands.ReplaceStyleTemplateCommand.ProvideCurrentStyle(SceneNode targetElement, IType targetType, PropertyReference targetPropertyReference, Boolean allowDefaultStyle, IList`1& auxiliaryResources)
   at Microsoft.VisualStudio.DesignTools.XamlDesigner.Commands.EditCopyOfStyleCommand.get_IsEnabled()
   at Microsoft.VisualStudio.DesignTools.Utility.Commands.Command.GetProperty(String propertyName, Object defaultValue)
   at Microsoft.VisualStudio.DesignTools.XamlDesigner.Commands.ReplaceStyleTemplateCommand.GetProperty(String propertyName)
   at Microsoft.VisualStudio.DesignTools.Designer.Views.SceneView.UpdateCommandState(IEnumerable`1 commandNames, Boolean forceRefresh)
   at Microsoft.VisualStudio.DesignTools.Designer.Views.SceneView.SelectionManager_LateActiveSceneUpdatePhase(Object sender, SceneUpdatePhaseEventArgs args)
   at Microsoft.VisualStudio.DesignTools.Designer.ViewModel.SceneUpdatePhaseEventHandler.Invoke(Object sender, SceneUpdatePhaseEventArgs e)
   at Microsoft.VisualStudio.DesignTools.Designer.ViewModel.Selection.SelectionManager.FireLateActiveSceneUpdatePhase(SceneUpdatePhaseEventArgs args)
   at Microsoft.VisualStudio.DesignTools.Designer.Views.SceneViewUpdateScheduleTask.UpdateLate()
   at Microsoft.VisualStudio.DesignTools.Utility.Scheduler.ScheduleTask.Update()
   at Microsoft.VisualStudio.DesignTools.Utility.Scheduler.SchedulingService.DispatchTasksAtPriority(DispatcherPriority priority)
   at Microsoft.VisualStudio.DesignTools.Utility.Scheduler.SchedulingService.DispatcherToken.Dispatch(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.RunApplication()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.DesignProcessViewProvider.AppContainerDesignerProcessRun(String[] activationContextArgs)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.DesignProcessViewProvider.<>c__DisplayClass3_0.<applicationView_Activated>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by APopatanasov** [comment] 2017-05-26 15:34
@schnitty It seems the provided stack trace is the same as the one in the image from your initial response. We [have found a workaround](https://github.com/telerik/UI-For-UWP/pull/98) that should resolve the issue, however it is still not merged. You could still check it by applying it locally on your side and [building a nuget of your own](https://github.com/telerik/UI-For-UWP/pull/98). 

You could also wait for the pull request to be merged and that fix will be available with our next nuget that will be uploaded.

Hope this will help you.

**Comment by schnitty** [comment] 2017-05-27 00:49
Thanks @APopatanasov I'm ok with building my own nugget if I need it sooner than you can get it merged in. If you can also get a fix/workaround for #83 Then that would be great

**Comment by APopatanasov** [comment] 2017-05-29 08:08
@schnitty We have merged the pull request. Your feedback about the issue and if it is resolved after the merged changes is highly appreciated. So, please let us know if you are still able to reproduce the issue after the merged changes.

**Comment by schnitty** [comment] 2017-05-29 17:42
Ok, so I have loaded the 1.0.0.3 nuget package into my package feed.  Will let you know I get on.

**Comment by schnitty** [comment] 2017-05-29 18:25
Is still get the same problem with the latest version 1.0.0.3.

**Comment by APopatanasov** [comment] 2017-05-29 19:56
@schnitty Could you please confirm the issue with version 1.0.0.3 is reproduced with the steps provided in your initial response? Please, be aware that we were not able to reproduce the mentioned issue in VS - only the one in Blend #96 (as they were similar our suggestion was that fixing the Blend issue will fix the VS as well) and providing a video that demonstrates it will be of help for us. 

Also, we will test the package further on our side in order to be sure that no other issues are introduced with it.

**Comment by schnitty** [comment] 2017-05-29 20:38
After having done a few more hours work I can confirm that I no longer get a designer crash in either Blend or VS with 1.0.0.3 when repeating the exact steps in my initial response.

I do however get the same exception in Blend and VS on occasion when selecting RadialGauge sub elements within the Objects and Timeline and Document Outline respectively.  I can create that as a separate issue if you prefer.

I'll try and get a screen recording of it happening

**Comment by APopatanasov** [comment] 2017-05-30 06:16
Providing a screen recording will be really helpful for us as we are still not able to reproduce that particular issue with the selection of the inner elements of RadRadialGauge.

**Comment by schnitty** [comment] 2017-05-30 06:56
@APopatanasov I was able to reproduce and have recorded a video, what is the best way for me to get it to you? It is probably my bosses preference not to post it to a public forum.  it's 5MB and 50s

**Comment by APopatanasov** [comment] 2017-05-30 08:01
You can send me the video to my email atanas.popatanasov@telerik.com.

**Comment by APopatanasov** [comment] 2017-05-30 08:27
Thanks for the video. We will try to reproduce the demonstrates issue on our side. As soon as we have some more information we will let you know.

**Comment by APopatanasov** [comment] 2017-05-30 12:44
@schnitty We have tried to reproduce the issue both with version 1.0.0.2 and 1.0.0.3 of the nuget package and following the provided steps but without any success. Attached you could find a sample we used for our investigation. Could you please confirm you are reproducing the issue with the sample on your side as well? If you are not able to reproduce it with the sample, please try to modify it in order to replicate your exact scenario and send the project back to us, so we could investigate it further?

[App1.zip](https://github.com/telerik/UI-For-UWP/files/1038293/App1.zip)

**Comment by schnitty** [comment] 2017-05-31 00:38
I'll take a look today and see if I can get you a simple project that has the repro.

**Comment by schnitty** [comment] 2017-05-31 08:47
I haven't been able to reproduce it in the project that you sent me but it is happening in the project that I am working on.  I spent some time trying to isolate it but haven't been able to yet.  For everyone's benefit I'll outline what I have done.

Theory 1: Using DI via autofac to inject the viewmodel may mean that the designer doesn't have proper access to the viewmodel or viewmodel is null thus causing some issues.
When I changed my project to instead set the DataContext to the view model in the XAML I was still able to reproduce the problem in my project.

Theory 2: using x:Bind to bind values is causing the problem
When I updated your sample project to use a ViewModel and bind to data using x:Bind I wasn't able to reproduce the issue.

Theory 3: Creators update is causing it
When I updated your sample project to Creators Update I wasn't able to reproduce the issue.

So at the moment I can reproduce in my project but not in the sample.  It could be any number of things I guess but at this stage seems related to the specifics of my project.  Will let you know if I discover anything else in the coming days.

**Comment by APopatanasov** [comment] 2017-05-31 10:17
Thank you for sharing this information with us. Unfortunately, without being able to reproduce the exact scenario we are not able to continue with our investigation. When you have some additional information please, let us know. 😊

**Comment by schnitty** [comment] 2017-06-16 01:27
I am getting the same problem now on controls that aren't telerik.  I get the same exception getting thrown from the ImageEx control from the UWP Toolkit.  So i'm now firming on it being a Visual Studio 2017 / Blend 2017 problem.  VS has always been pretty stable in my previous experience this version I have had nothing but problems, very buggy.  Today in Blend with the latest update it keeps thinking I want to move things in the visual tree when I am just trying to expand.  Takes about five clicks to get it just right.  I can't work like this.  I think I will go back to VS2015.  Just thought I would comment for other's benefit.

**Comment by APopatanasov** [comment] 2017-06-16 07:02
Hi @schnitty,
Thanks for sharing this information with us. It is really helpful to know that the issue is not strictly connected with our controls. We suggest you to submit the issue to the Visual Studio Team as it seems it is something strictly connected with your scenario that breaks the designer. On the following link you could share your feedback them:
[https://connect.microsoft.com/VisualStudio/Feedback](https://connect.microsoft.com/VisualStudio/Feedback)

I will close this issue. If you have any other concerns or feedback regarding the UI for UWP controls do not hesitate to let us know. 😊

**Closed by APopatanasov** 2017-06-16 07:02 UTC
Labels: bug, state:need repro

**Comment by schnitty** [comment] 2017-06-20 01:08
@APopatanasov 
I have a somewhat simplified reproducible project.
I have sent it to your email address.
[TelerikXamlDesignerBug.zip](https://github.com/telerik/UI-For-UWP/files/1086712/TelerikXamlDesignerBug.zip)

**Comment by schnitty** [comment] 2017-06-20 01:22
@APopatanasov 
Not sure on the prime cause but I think it has something to do with Template10 and using third party controls.

I have also posted the issue with Template10 and UWP Community Toolkit
https://github.com/Windows-XAML/Template10/issues/1506
https://github.com/Microsoft/UWPCommunityToolkit/issues/1225

Will do so with Microsoft as well.

**Comment by schnitty** [comment] 2017-06-20 03:11
[TelerikXamlDesignerBugs.zip](https://github.com/telerik/UI-For-UWP/files/1086902/TelerikXamlDesignerBugs.zip)

I accidentally uploaded the wrong repro before.
This is the correct one

**Comment by APopatanasov** [comment] 2017-06-20 10:16
Hi @schnitty , 
As the issue is not directly connected to the controls we could not tell what exactly is causing it Hope the guys from the community will help to resolve it.

**Comment by schnitty** [comment] 2017-06-20 23:42
Ok, thanks.
