### ISSUE TITLE
InlineButton Repeat behavior not working

### ISSUE THREAD

**Issue by jeffklawiter** [telerik/UI-For-UWP#406] opened 2019-07-22 23:45 UTC
### Description
InlineButton will not repeat calls to Clicked when IsRepeatingEnabled is true
### Steps to Reproduce

1. Add an InlineButton to an interface with IsRepeatingEnabled=true and a click handler
2. Run the application and hold a long press on the button
3. Observe click only is called once

### Expected Behavior
Click should be called once, then a repeating sequence of the defined Interval after the defined RepeatDelay
### Actual Behavior
Click is only called once and repeat behavior never occurs
### Basic Information
The cause of this issue can be found in the source code where the automationPeer.Invoke() is specifically not called in UWP builds
https://github.com/telerik/UI-For-UWP/blob/master/Controls/Primitives/Primitives.UWP/Common/Controls/InlineButton.cs#L499
I'm sure there was a reason for this at some point but I do not know what it is. Fixing it should be simple, but without knowing the reason why the precompiler directive was added whatever it fixed may rise again.

- Version with issue: 1.0.1.6
- Last known good version: Not Known
- IDE: Visual Studio 2019
- UWP SDK: Most likely all. Tested with target 1809 and min 10586
- Nuget Packages: Telerik.UI.for.UniversalWindowsPlatform

### Reproduction Link
https://github.com/jeffklawiter/inlinebutton-repeat-repro

**Comment by APopatanasov** [comment] 2019-07-23 09:57
Hi @jeffklawiter ,

Thank you for the detailed information and sample project. Using it I was able to reproduce the observed by you behavior. 

Unfortunately, I cannot tell for sure what might be the reason for not executing the Invoke method of the peer for UWP. The only scenario that could fail and is not handled is when the Narrotor (that works with the Automation peers) is on. The narrator works only with the peer associated with the button and because of that when Invoke is called an exception is thrown. I am glad to inform you that I have applied a fix (#407) for that scenario as well - when the Narrator is on the peers associated with the Button are used and thus no exception is thrown.

You can cherry pick the fix and test it on your side. If everything is working as expected I will merge the fix and it will be available with the next official release of the nuget scheduled for September.

I am looking forward to hearing from you.

**Comment by jeffklawiter** [comment] 2019-07-23 13:12
Tested it out on a Surface and Desktop, worked as expected on both

**Comment by APopatanasov** [comment] 2019-07-23 15:09
@jeffklawiter Thanks for your answer. As everything seems to be working as expected I will proceed and merge the PR. As mentioned above the fix will be included in the next nuget package scheduled for September.

Thanks again for your help.

**Closed** 2019-09-11 12:19 UTC
Labels: area:primitives, bug, effort: easy (hours), severity:medium, status: Done
