### ISSUE TITLE
Project build failed with 1.0.0.1 nuget package 

### ISSUE THREAD

**Issue by acsatis** [telerik/UI-For-UWP#37] opened 2017-02-16 15:18 UTC
![image](https://cloud.githubusercontent.com/assets/4085915/23027075/883811e8-f463-11e6-8830-30855c537505.png)

My project cannot build with the 1.0.0.1 nuget package. Can you help me?

**Comment by APopatanasov** [comment] 2017-03-08 13:27
Hi @acsatis ,

We have tried many different scenarios in order to reproduce the observed by you errors with our nuget package, but without any success - everything was building as expected on our side.

Could you please, send us a sample project that demonstrates that errors, so we could be able to investigate them further? Without being able to observe the errors on our side we could not tell what might be causing them.

Thanks in advance.

**Comment by LanceMcCarthy** [comment] 2017-03-10 20:50
@acsatis I have seen this before, clearing the Nuget cache fixed it for me.

**Comment by acsatis** [comment] 2018-10-28 11:54
![image](https://user-images.githubusercontent.com/4085915/47615537-69448e80-dab0-11e8-8c8c-24a724e21f4f.png)

In this case you can see the problem. This is not working for me. I tried to clear the nuget cache as well, but this is not worked for me.

**Comment by APopatanasov** [comment] 2018-10-29 13:19
@acsatis I have followed the schema and created a sample project. However, I am still not able to reproduce the issue. Could you please, check the attached sample and let me know if I have missed something?
[HeadProject.zip](https://github.com/telerik/UI-For-UWP/files/2525040/HeadProject.zip)

**Comment by acsatis** [comment] 2018-10-29 15:54
Thanks for quick response. I think this problem depends on the template resources. My project is much more bigger, than this sample. I'll try to remove everything except the Page with Telerik controls and I'll attach my project to this issue.

**Comment by acsatis** [comment] 2019-06-05 10:30
with version 1.0.1.5 I don't have any problem with this. Thanks, @APopatanasov , you can close the ticket.

**Comment by APopatanasov** [comment] 2019-06-05 10:37
@APopatanasov Thanks for confirming everything is working as expected now. I am closing the issue as requested.

**Closed by APopatanasov** 2019-06-05 10:37 UTC
Labels: bug, need more info, state:need repro
