### ISSUE TITLE
Charts - missing chart grid lines and bad colors on Windows ver. 1703 (Creators Update)

### ISSUE THREAD

**Issue by Hujerek** [telerik/UI-For-UWP#80] opened 2017-04-26 11:06 UTC
Even the problem with missing parts of series-lines was fixed by "chart clip fix" introduced a few days ago, there is still an issue with **wrong colors of axes** and **chart grid lines not drawn** on latest W10 build (on both PC desktop and mobile).

The problem with wrong color of axes is more noticeable when Dark theme is used.
Instead of white they are rather black. 
![charts-bug](https://cloud.githubusercontent.com/assets/26966273/25431191/dbe93b1c-2a7f-11e7-82c1-1fd2dc402206.png)
![charts-ok](https://cloud.githubusercontent.com/assets/26966273/25431502/17ce149e-2a81-11e7-9421-f4203b513bfe.png)

Second, chart grid lines are missing completely.
![gridlines-bug](https://cloud.githubusercontent.com/assets/26966273/25431385/b35e2828-2a80-11e7-9d83-4a2cfd3ebadd.png)
![gridlines-ok](https://cloud.githubusercontent.com/assets/26966273/25431386/b364b68e-2a80-11e7-9942-67cb274c725d.png)

Both issues can be simply reproduced using SDKExamples.UWP project build e.g. under VS2017 for x86 and running on machine with W10 v.1703.

**Comment by APopatanasov** [comment] 2017-04-28 15:36
Hi @Hujerek ,
A [fix ](https://github.com/telerik/UI-For-UWP/pull/81) has been merged. We hope it will work for you.

**Comment by Hujerek** [comment] 2017-05-02 08:37
Yes, it works. Thanks.
Just curious, did you also check another places in the code where the "new logic" for Canvas positioning can be an issue? And, is this "behaviour" a bug or rather some change in latest Microsoft's SDK?

**Comment by APopatanasov** [comment] 2017-05-02 19:32
Hi @Hujerek ,
We have applied another [fix ](https://github.com/telerik/UI-For-UWP/pull/87/commits/fc1c0a072fc418814ee801e57e7cc12cf22159a5)for the observed by you issues of the Chart control - no changes should be observed on your side with this new fix and everything should be working as expected as with the other fixes. Also, the issues have been confirmed to be caused by the Creators Update - we hope that with this fix no other issues will be observed with the Canvases.

**Closed** 2017-05-10 07:38 UTC
Labels: status: InProgress
