### ISSUE TITLE
NullReferenceException thrown when grouping RadDataGrid by EF property that's null

### ISSUE THREAD

**Issue by WDev20** [telerik/UI-For-UWP#207] opened 2017-12-15 19:41 UTC
When you scroll the RadDataGrid horizontally after grouping by an EF property column where one or more of the rows has that property set to null, the application crashes with the following exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Telerik.UI.Xaml.Controls.Grid.DataGridColumn.PrepareColumnHeaderCell(GridHeaderCellModel cell)
   at Telerik.UI.Xaml.Controls.Grid.XamlGridHeaderCellGenerator.PrepareContainerForItem(GridHeaderCellModel decorator)
   at Telerik.UI.Xaml.Controls.Grid.ColumnModelGenerator.PrepareContainerForItem(GridHeaderCellModel decorator)
   at Telerik.UI.Xaml.Controls.Grid.ColumnHeaderPool.GenerateAndPrepareContainer(ItemInfo&

**Comment by APopatanasov** [comment] 2017-12-18 08:37
Hi @WDev20 ,

Using the provided description I was not able to hit the observed NullReferenceException. However, I was able to hit an InvalidCastException when I grouped column with null value. I am not sure if both exceptions are connected. The InvalidCastException is caused by the way the groups are created. In order to resolve that issue inside the **AddItem** method part of the **DataEngine** class the check for null for the groupName is not needed and could be commented:
https://github.com/telerik/UI-For-UWP/blob/b420c29f3222ec6c34557d468b7787056a4750bc/Controls/Data.UWP/Data/Engine/PivotGrouping/DataEngine.cs#L1011

Could you please, give a try to that fix at your side and let me know if it also resolves the NullReferenceException as well as I am not able to reproduce that exception? If the fix resolves the issue feel free, to make a pull request and I will be glad to review it. 

However, if the exception remains could you please, send a project that reproduces it - thus I will be able to investigate it further and provide you with additional information what is causing it.

**Comment by WDev20** [comment] 2017-12-19 18:04
Hi APopatanasov,

Apparently the issue has disappeared after commenting out that piece of code.

**Comment by APopatanasov** [comment] 2017-12-21 15:33
@WDev20  that is really great. Thank you for your help. Currently, I cannot think of any reason why the suggested fix cannot be applied.  I see that that you have made pull requests - #209  and #208. Before I can review them can you please, sign the [Telerik UI for UWP Contribution License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSfQAzVxnnfwRQmtJCVmB41_ig1gYow--Gr8qLvaDxJRNHPtUQ/viewform).

Thank you again for your collaboration. 🥇

**Comment by WDev20** [comment] 2017-12-21 18:07
@APopatanasov, I've signed the agreement.

**Comment by APopatanasov** [comment] 2017-12-22 12:06
Fixed with : #212

**Closed** 2018-01-09 11:51 UTC
Labels: CLA:NO, area:grid, bug, effort: easy (hours), severity:high, status: Done
