### ISSUE TITLE
Chart axes lines, ticks, & labels aren't theme aware by default

### ISSUE THREAD

**Issue by mrlacey** [telerik/UI-For-UWP#147] opened 2017-07-17 18:21 UTC
X-Ref https://github.com/Microsoft/WindowsTemplateStudio/issues/808#issuecomment-315637915

The lines, labels, and ticks on a chart aren't theme aware by default but labels on the chart are. (See link above for example screenshots.)

**Comment by APopatanasov** [comment] 2017-07-17 19:28
Hi @mrlacey ,

Thanks for bringing this to our attention. I confirm it is a bug in the Chart control. We will try to resolve it as soon as possible. In the meantime you could use the fix you have found. 😊

**Comment by mrlacey** [comment] 2017-07-17 19:53
Thanks. Will update WTS when you release a fix

**Comment by APopatanasov** [comment] 2017-07-21 07:10
Hi @mrlacey ,

We have applied a small fix for the Chart control connected with the dynamic changing of the themes that doesn't resolve the major issue. However, after further investigating the issue we have found that it is actually only observed on machines with Creators update. Not only the Chart control, but all controls from the repository are affected by it.

Basically, in the implementation of our Themes we have ResourseDictionaries with some resources (brushes for example) merged inside the ResourceDictionary of the specific theme (Dark or Light) . After the theme is changed the resources that are part of the merged dictionary are not applied. This issue seems to be introduced with the Creators Update as it is working as expected with the Anniversary. 

We will let you know when we have some additional information.

**Comment by mrlacey** [comment] 2017-07-21 10:47
@APopatanasov  thanks for the update

**Comment by APopatanasov** [comment] 2017-08-11 08:24
Hi @mrlacey ,

Microsoft have confirmed the issue is on their side and it is introduced with the Creators Update. They are working on resolving it. Hopefully, the fix will be available with the Fall’s Creators Update.

Do not hesitate to contact us if you hit the issue with some of the other controls. We will try to provide you with a workaround until the major issue gets fixed.

**Comment by mrlacey** [comment] 2017-08-11 13:46
Thanks for the update. Will keep our workaround in place for the foreseeable future then.

**Comment by mrlacey** [comment] 2018-06-22 11:48
@APopatanasov following up on this again.
Is Microsoft's confirmation of this public?
Is there any timeline/roadmap for them resolving it?
Can you do anything for a workaround?
As Creators Update is now on a much smaller number of machines, this impacts a lot more end users. Does Telerik have a timeline for setting CU as the minimum supported version and therefore need to address this themselves?

At the moment, to use the charts and have it support theme-awareness requires setting custom styles for every line displayed. It'd be great if we could fix this once and not force every developer who uses the control to do extra work.

**Comment by APopatanasov** [comment] 2018-06-22 13:35
@mrlacey I can confirm the issue we have logged to Microsoft is fixed. We have logged it using a sample project that was simulating our theming mechanism without using any of the controls. The fact that I am not observing any affect on our controls makes me think the problem is now in the controls itself. 

I totally agree that applying such workaround and doing some extra work by the developers is not acceptable. I will mark the issue with height priority. Once  a fix is applied I will let you know with which version of the nuget it will be available.

**Comment by APopatanasov** [comment] 2018-06-25 10:19
@mrlacey It seems the example that was initially sent to Microsoft was not demonstrating our complete theming mechanism and because of that the issue that was fixed was not the one we are observing in our themes.

I have prepared another sample that I believe now fully demonstrates the issue and we will contact the Microsoft guys again. 

I apologize for the inconvenience the issue is causing. Currently, we cannot apply a fix or workaround on our side because we will break our theming functionality. I hope the issue will be confirmed by Microsoft and it will be fixed.

Once I have some more information to share I will let you know.

**Comment by mrlacey** [comment] 2018-06-25 10:48
thanks for the update

**Comment by APopatanasov** [comment] 2018-07-03 14:41
@mrlacey Good news. The issue has been confirmed by Microsoft. They have stated that a fix will be applied with their next official release that is stated for early October. 

Again, I apologize for the inconvenience the issue might be causing.

**Comment by mrlacey** [comment] 2018-07-03 15:19
@APopatanasov  And what will the fix involve? Will it retrospectively fix the issue when running on machines with Windows versions from Creators Update to the April 2018 releases? Or will it only affect when running on the new release?

**Comment by APopatanasov** [comment] 2018-07-03 15:21
@mrlacey I cannot tell for sure, but I believe it will affect only machines running the new release.

**Comment by mrlacey** [comment] 2018-07-03 15:24
So anyone with machines running the three affected releases ([~95% of current machines](http://blog.adduplex.com/2018/05/windows-device-statistics-for-may-2018.html)) then the workarounds will still be needed.

**Comment by APopatanasov** [comment] 2018-07-04 07:43
I do agree this seems a little inconvenient at this point. At the same time, the high adoption rates of the latest versions of Windows 10 seem to play favorable role. 

We were offered workaround, which we could incorporate in the suite, however the suggested workaround uses the MergedDictionaries collection and merge 3 new dictionaries inside the dictionary that holds the styles of the controls. Inside each new dictionary in their ThemeDictionaries collection 3 more dictionaries are added for each theme (Light, Dark, HighContrast). That nearly doubles the number of dictionaries used in our theming mechanism. This is why, we cannot add such thing in the suite. 

So we will suggest that you stick with the workaround for a few more months, until it gets fixed and adopted, unless you have the means (hey @crutkas) to ask Microsoft to backport the fix

**Comment by stevenbrix** [comment] 2018-07-05 21:11
Steven from Microsoft here. Thank you for reporting this issue, what version of Windows 10 is the app targeting?

**Comment by APopatanasov** [comment] 2018-07-27 15:18
@mrlacey I have some good news. I have applied a new approach (proposed by Microsoft) for merging the theme dictionaries. Using it the observed issue no longer reproduces and everything is working as expected in all versions of Windows.

Once the the pull request (#301) gets reviewed it will be merged in development and the fix will be available with our next official release in September. I hope that the time frame will be acceptable for you.

**Closed** 2018-08-24 13:02 UTC
Labels: bug, effort: medium (days), severity:critical, status: Done

**Comment by APopatanasov** [comment] 2018-09-12 13:11
@mrlacey We have just released and a [nuget ](https://www.nuget.org/packages/Telerik.UI.for.UniversalWindowsPlatform/1.0.1.1) that includes the fix is available. As mentioned in my previous reply the included fix works in all versions of Windows.

Have a good rest of the week. 😄
