### ISSUE TITLE
Visual Studio 2017 (Not responding) with Telerik/UI & Windows Template Studio

### ISSUE THREAD

**Issue by placeitsolution** [telerik/UI-For-UWP#145] opened 2017-07-14 10:16 UTC
Visual Studio 2017 freezes (Not responding)) when "telerik/UI-For-UWP" is used with Windows Template Studio. I tried to add/change properties to the calendar control in XAML (<telerikInput:RadCalendar />) and it just freezes every time. Attached is an image.

![freeze](https://user-images.githubusercontent.com/27952823/28208244-6c25732c-68aa-11e7-8be5-f951fc82e822.PNG)

Vinod

**Comment by APopatanasov** [comment] 2017-07-14 13:09
Hi @placeitsolution ,

We were not able to reproduce the described by you behavior. Could you please provide us some more information? What is the exact version of VS that you are using? Is the issue only reproduced when the Templates are used or it could be reproduced outside of the Templates (in a simple sample project)? What is the target version of your application?

**Comment by placeitsolution** [comment] 2017-07-14 17:01
Hi, The issue is reproduced ONLY when using the template. The version is .NET 4.6.2 running on Visual Studio 2017 Enterprise and the OS is Windows 10 Enterprise (v 1703, Build 15063.483). I installed the Telerik UI via Nuget. The project (sample) that keeps hanging is attached below.

[App9.zip](https://github.com/telerik/UI-For-UWP/files/1149041/App9.zip)
.

**Comment by APopatanasov** [comment] 2017-07-14 21:14
@placeitsolution we were not able to reproduce again the observed issue using the provided additional information. Attached you could find an application we have created on our side. Could you please check it and let us know if the issue is reproduced with it?
[App2.zip](https://github.com/telerik/UI-For-UWP/files/1149680/App2.zip)

**Comment by placeitsolution** [comment] 2017-07-15 04:30
@APopatanasov  thanks for the response and sending me the file. But as soon as I try to work with the control by clicking it or when I try to edit XAML it freezes. Also the property window stays empty.

![freeze-2](https://user-images.githubusercontent.com/27952823/28236419-f518433c-6943-11e7-9449-5eb80b716a27.png)

**Comment by placeitsolution** [comment] 2017-07-17 03:55
@APopatanasov, It does work on other machines. I think there is some corruption on my machine which was running perfectly before. Sorry to have bothered you and thanks for the response.

**Comment by APopatanasov** [comment] 2017-07-17 06:13
@placeitsolution Thanks for providing that information to us. I will close the issue for now as it seems it is related to some issues caused by your machine. If you have any other concerns please, let us know.

**Closed by APopatanasov** 2017-07-17 06:13 UTC
Labels: need more info
